### PR TITLE
Update .gitignore to include more build artifacts.

### PR DESCRIPTION
**Pull request by lesamouraipourpre**

### CODE REVIEW

**Comment by jposada202020** [comment]
@lesamouraipourpre just to understand, this will include artifacts when doing a PR and when releasing ?
Is there a way that I could test this? I have some libraries in the community bundle, so I could test with those.

Lt me know 

Thanks for this :)

**Comment by lesamouraipourpre** [comment]
After doing the build locally with `.build.sh` and running `git status`:
```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        build-circuitpython-community-bundle-6.x-mpy-20210506.zip/
        build-circuitpython-community-bundle-7.x-mpy-20210506.zip/
        build-circuitpython-community-bundle-examples-20210506.zip/
        build-circuitpython-community-bundle-py-20210506.zip/
        build_deps/
```
There is no need to upload these new build artifacts to github. That is what this change to `.gitignore` will prevent.

**Comment by jposada202020** [comment]
Understood.. will do.  Thanks again

**Review by jposada202020 — APPROVED** [review]
Thanks, yes this two directories are created when building the library. While creating the community bundle, these two directories are created.

**Pull request merged**
