### PR TITLE
Add functools library

### PR DESCRIPTION
**Pull request by tekktrik**
Adds a CircuitPython library that emulates the functionality of CPython's `functools`.  So far I've got `cache` but I want to try adding `total_ordering` and `partial`.

### CODE REVIEW

**Comment by dhalbert** [comment]
Have you seen https://github.com/micropython/micropython-lib/tree/master/python-stdlib/functools, and not just that, but the whole repo? It has reduced-functionality versions of many things in CPython.

**Comment by tekktrik** [comment]
Oh no, I didn't, thanks for letting me know!  Maybe I can fork that and add it there.

**Comment by tekktrik** [comment]
I did try to add my `csv` implementation there but it's still waiting.  I'll take a look, but I do like that `partial` implementation!

**Comment by dastels** [comment]
Excellent!  I played around with partials [in this guide](https://learn.adafruit.com/partials-in-circuitpython).

**Comment by tekktrik** [comment]
Added `partial`!  Haven't tested it yet but it seems to check out.

**Comment by Neradoc** [comment]
Can you update circuitpython_community_library_list.md with it too ?

**Comment by tekktrik** [comment]
Good catch!  Added it to the list.

**Comment by tekktrik** [comment]
Is anything still pending on this?

**Review by kattni — APPROVED** [review]
Looks good to me! Congrats on being the 350th CircuitPython library!!

**Pull request merged**
