### PR TITLE
Added driver for Adafruit Soundboards

### PR DESCRIPTION
**Pull request by mmabey**

### CODE REVIEW

**Comment by ladyada** [comment]
neat!

**Comment by tannewt** [comment]
Hi @mmabey what board are you using this with? It looks like its written for MicroPython but this bundle is intended for libraries that support CircuitPython instead. I'm sure the MicroPython folks would appreciate the library as well but I'm not sure how they keep track of them all.

We'd love it if you would port to CircuitPython as well but thats up to you.

Unrelatedly, I noticed you had dummy files to make Sphinx happy for machine and such. There is actually a way to have sphinx automock imports for you. More info [here](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autodoc_mock_imports)

Cheers,
Scott

**Comment by mmabey** [comment]
Hi @tannewt, yes I wrote it for MicroPython, but only because the two boards I currently own are the original pyboard and the WiPy (v1), neither of which have chips supported by CircuitPython. I tested the library on both boards and didn't have any problems. Then I took a look at the CircuitPython API docs to make sure that everything should be compatible with both, but I know that's no substitute for running it on the actual hardware, and I totally understand you wanting to make sure everything is good to go before adding it to the bundle. As I said, the only reason I didn't do so myself is because of the limitations of the hardware I have.

The other reason I submitted this as a CircuitPython library is made sense given it's a driver for an Adafruit product. I plan to add it to the MircoPython [list of libraries for external devices](http://wiki.micropython.org/Home#Libraries-for-External-Devices), I just haven't gotten to that yet.

Thanks for the tip on the mock imports! I did a cursory look for something like that, but didn't find anything, so I figured I'd do it myself. I'll definitely use that and update the PR.

**Comment by tannewt** [comment]
Ok cool! We've replaced `machine` with a series of [other hardware APIs](https://circuitpython.readthedocs.io/en/stable/shared-bindings/index.html#modules) that are uniform across all of the devices we support.

If you are interested in port this to CircuitPython we'd be happy to hook you up with a Feather M0 Express or Metro M0 Express. Please email me (scott@adafruit.com) to make that happen. Thanks!

**Comment by mmabey** [comment]
Hi @tannewt, just wanted to give you a quick update. I've done some work on porting the driver to CircuitPython, but I've run into a couple errors. When I use the `.py` file, I get a memory error. When I convert to `.mpy`, it says it's in an invalid format. I still have a couple things I want to try on my own, but I won't be able to work on it again for another week or so. Once I'm able to get back into it again, if I can't fix whatever the problem is, I'll reach out; maybe you'll be able to see something I can't.

BTW, thanks again for sending me the awesome boards. They arrived on Friday and I've been having fun playing with them. That really was super generous of you. I'll do my best to pay it back in drivers :grin:

**Comment by tannewt** [comment]
@mmabey no rush on our end! The mpy version check will fail if you are using a released version of CircuitPython such as 1.0 with mpy-cross from master because its been updated. Try using mpy-cross from master and loading CircuitPython itself from there as well.

**Comment by tannewt** [comment]
@mmabey Any update on the CircuitPython drivers?

**Comment by mmabey** [comment]
@tannewt Yes! I got it working last night, but I need to do some more testing before I'm comfortable pushing.

I've run into one problem that I think is a result of there not being a `UART.any()` method in CircuitPython. When I need to flush the buffer, calling `UART.read()` seems to hang unpredictably when I call it from my code, but not when I call it manually from the REPL. I know that `UART.read()` is written to have a timeout and return `None` if no data is available, but it seems something is causing it to hang when called. Any suggestions? Would it help if I pushed the current version for you to look at?

**Comment by tannewt** [comment]
Yay! Yeah, please push the code somewhere and I am happy to take a look. You can ping me on [Discord](http://adafru.it/discord) to discuss it as well. Thanks!

**Comment by mmabey** [comment]
Just pushed current version to https://github.com/mmabey/Adafruit_Soundboard. The main problem seems to be happening in the [_flush_uart_input()](https://github.com/mmabey/Adafruit_Soundboard/blob/master/adafruit_soundboard.py#L118) method.

**Comment by tannewt** [comment]
Instead of merging, could you rebase to the lastest master? Thanks for your persistence with this!

**Comment by mmabey** [comment]
Yes I can. I just didn't want to force push, but only because I know it's frowned upon in the general case

**Comment by mmabey** [comment]
Hope it's okay I squashed the commits. Figured it would be cleaner with just one. Let me know if you see any other issues.

**Comment by tannewt** [comment]
Force push is ok for pull requests because no one else should base their code on it. Looks good now!

**Pull request merged**
