### PR TITLE
Adds tzdb

### PR DESCRIPTION
**Pull request by evindunn**
IANA timezone database support for adafruit_datetime

https://circuitpython-tzdb.readthedocs.io/en/latest/api.html

### CODE REVIEW

**Comment by Neradoc** [comment]
Hello, the circuitpython_community_library_list.md libraries list is currently managed manually, could you edit it to add your module and the relevant links ? Thank you.

**Comment by evindunn** [comment]
@Neradoc done, thanks!

**Comment by FoamyGuy** [comment]
@evindunn I think there is part of the automation scrips somewhere that are expecting the tag names to follow sem versioning with no other characters.

Right now you newest release tag name is `v0.0.3`, I think the v might throw it off though. Can you make a new one with just the 3 numbers seperated by dots and no v or other characters?

**Comment by FoamyGuy** [comment]
@evindunn Ahh, nevermind I didn't look at the right thing I think the tag you have now is good.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thanks @evindunn great addition!

**Pull request merged**
