### PR TITLE
Update python and actions/checkout versions

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by tannewt** [comment]
I created this PR after seeing that we're building the 6.x bundle here still. It's in the build-tools version that was the last to support 3.6. Updating Python allows us to use newer build tools.

**Comment by KeithTheEE** [comment]
Looks good, only question I've got is why set it to `3.x` instead of `3.7`?

**Comment by kattni** [comment]
@KeithTheEE Because that means it will always use latest, instead of requiring an update every time there's a new release.

**Review by kattni — APPROVED** [review]

**Comment by tannewt** [comment]
@KeithTheEE I don't believe so. This copy of Python is just used for tooling, not verification of code.

**Pull request merged**
