### PR TITLE
Add RM3100 magnetometer library

### PR DESCRIPTION
**Pull request by furbrain**

### CODE REVIEW

**Comment by tekktrik** [comment]
This looks great!  It looks like the only issue is that you have an outdated version of the Community Bundle.  You can either rebase off of the current one, or resolve the conflict (you can do that latter on the GitHub website interface).  Let me know if you want help, or want me to do that if you'd prefer!

**Comment by furbrain** [comment]
Ok, I've resolved the changes. At some point I intend to switch my API to using a more adafruity access method (e.g. calling rm.magnetic rather than rm.get_last_reading()) - I presume it's ok to do this provided I update the docs etc.

**Comment by tekktrik** [comment]
Yup!  This is totally your library, feel free to change things as needed.  It'll be easy for people to understand changes using semver versioning, but that's all up to you!

**Review by tekktrik — APPROVED** [review]
Nice job!

**Pull request merged**
