### PR TITLE
Add CedarGrove WaveViz to helper library

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
CedarGrove WaveViz is a CircuitPython class that creates a positionable displayio.Group graphics widget from a synthio wave table.

https://github.com/CedarGroveStudios/CircuitPython_WaveViz

The soon-to-be-completed Playground note page: https://adafruit-playground.com/u/CGrover/pages/waveviz-plot-a-synthio-wave-table

### CODE REVIEW

**Review by tekktrik — CHANGES_REQUESTED** [review]
Looks like you only submitted the markdown update but not the submodule!

**Comment by CedarGroveStudios** [comment]
Well that’s confusing. I’ll have to retrace my steps. Thanks!

**Review by tekktrik — APPROVED** [review]
Groovy, you're all set, thanks!

**Comment by CedarGroveStudios** [comment]
Thank you!

**Pull request merged**
