### PR TITLE
Add ILI9163 driver.

### PR DESCRIPTION
**Pull request by ntavish**

### CODE REVIEW

**Comment by ladyada** [comment]
hmm do you mind rebasing and re-trying? it looks like 2 PRs came in at once and so you got de-synced?

**Comment by ntavish** [comment]
@ladyada done, fixing the other one too

**Comment by ladyada** [comment]
ok i think this needs to be force-pushed too - sorry for the complexity! its rare to have so many great contribs :)

**Comment by ntavish** [comment]
oh, yeah, my bad, sorry! I should have moved the lines int the previous PR in `.gitmodules` above(or below?) Should be fixed now.

**Comment by ladyada** [comment]
perfect. thankx!

**Pull request merged**
