### PR TITLE
Add Nunchuk

### PR DESCRIPTION
**Pull request by caternuson**
Add CircuitPython driver for Wii Remote Nunchuk.

### CODE REVIEW

**Comment by ladyada** [comment]
heya do you want to move this to Adafruit repo so we will maintain it?

**Comment by caternuson** [comment]
Awesome! Sure. I was just doing this as a side project to help out ATMakers. But if you want it in Adafruit repo, can do!

**Comment by ladyada** [comment]
sure, plz do the transfer

**Comment by caternuson** [comment]
OK. closing here. will PR over there.

**Pull request closed without merging**
