### PR TITLE
Add Candlesticks graphs

### PR DESCRIPTION
**Pull request by jposada202020**
This will allow to display candlestick information for stock market display information
image

### CODE REVIEW

**Comment by jposada202020** [comment]
@kmatch98, :) No `bitmaptools.draw_line` in this one

**Review by tannewt — CHANGES_REQUESTED** [review]
I think these both need releases.

**Comment by jposada202020** [comment]
Oh in my side, my bad I was waiting for danh jeje :) First time

**Comment by jposada202020** [comment]
Replaced by #65

**Pull request closed without merging**
