### PR TITLE
Add DebouncedButton

### PR DESCRIPTION
**Pull request by BradChan**

### CODE REVIEW

**Comment by ladyada** [comment]
hi sorry i didn't get to this earlier
please rename
https://github.com/BradChan/Adafruit_CircuitPython_DebouncedButton
to 
https://github.com/BradChan/BradChan_CircuitPython_DebouncedButton

because Adafruit did not author it :)

**Comment by kattni** [comment]
@BradChan Hi! Thanks for submitting this. As Ladyada requested, before we can include this in the Community Bundle, the library must be renamed to something not including Adafruit. You should be able to easily rename the repo through the settings. Depending on your comfort level with git/GitHub, it may make more sense to submit a new PR at that point, versus updating this one.

**Comment by dhalbert** [comment]
Alternatively you can rename it just to `CircuitPython_DebouncedButton`, which is the typical prefix for community-contributed  libraries.

**Comment by jposada202020** [comment]
Is the merge conflicts the only thing stopping this to be merged? I could that if @BradChan agrees. Let me know thanks

**Comment by lesamouraipourpre** [comment]
What does this offer that [Adafruit_CircuitPython_Debouncer](https://github.com/adafruit/Adafruit_CircuitPython_Debouncer) does not?

The `is_pressed` and `is_released` methods are extra but the information was accessible anyway.

The usage of `time.monotonic_ns()` has been removed from the original Debouncer code relying only on `time.monotonic()` which will have responsiveness issues after a few days of usage.

**Comment by jposada202020** [comment]
@BradChan what do you think, let us know your comments, thanks

**Comment by jepler** [comment]
@BradChan please feel free to open a fresh PR in the future if you return to this topic. Thanks!

**Pull request closed without merging**
