### PR TITLE
added driver library for the PCF85063A RTC

### PR DESCRIPTION
**Pull request by bablokb**
A library for the PCF85063A RTC found in various Pimoroni products (and cm4io-base).

### CODE REVIEW

**Comment by tekktrik** [comment]
I believe you'll need your `1.0.0` tag commit to match the one here for the CI to pass.  You can either force update the current commit in your repository  to `1.0.0` or create a `1.0.1` tag for it.  That shoooould fix the problem :)

**Comment by bablokb** [comment]
Thanks for the support (the reason for the failed check was not clear for me), I will try that.

**Comment by bablokb** [comment]
So I have created the 1.0.1 release/tag. How can I retrigger the CI-workflow?

**Comment by jposada202020** [comment]
Hello bablokb. I have just done it, but for further reference is under Actions, Re0Run Workflows. Cheers :)

**Comment by bablokb** [comment]
I seem to be blind, I had looked there before and I can't see it. Anyhow, thanks for restarting the workflow.

**Review by tekktrik — APPROVED** [review]
Looks good to me, thanks for the new library!

**Pull request merged**
