### PR TITLE
Added CircuitPython_Button_Handler.

### PR DESCRIPTION
**Pull request by EGJ-Moorington**
Added [CircuitPython_Button_Handler](https://github.com/EGJ-Moorington/CircuitPython_Button_Handler.git), a helper library that handles different types of button presses such as short presses, long presses, double presses and holding actions.

### CODE REVIEW

**Comment by dastels** [comment]
I suggest using the adafruit_debouncer module rather than using sleep to implement a debounce.

**Comment by dastels** [comment]
Actually, it might be even better to add functionality to adafruit_debouncer.Button.

**Comment by dhalbert** [comment]
`keypad` can also be used as the basis of this on boards that support it (most): it provides timestamped button up/down events without any Python-based polling or delays. https://learn.adafruit.com/key-pad-matrix-scanning-in-circuitpython

**Comment by EGJ-Moorington** [comment]
> `keypad` can also be used as the basis of this on boards that support it (most do): it provides timestamped button up/down events without any Python-based polling or delays. https://learn.adafruit.com/key-pad-matrix-scanning-in-circuitpython

Thanks for the feedback! Now I'm left wondering if I should make the version based on `keypad` a separate library (so that non-compatible boards can still use the library) or just make it Button_Handler 2.0.0.
It could also be possible to add functionality that doesn't use `keypad` via a 
```
try:
  import keypad
except ImportError:
  # Implementation for non-compatible boards
else:
  # Implementation for compatible boards
```
correct?

**Comment by dhalbert** [comment]
Boards without `keypad` are tight on space, so importing a dual-compatible version might bring in unused code which would use up RAM. Or you can refactor it so there are two different files to import.

**Comment by EGJ-Moorington** [comment]
Based on that, could
```
try:
  import keypad
except ImportError:
  import non_keypad_using_lib_ver
else:
  import lib_ver_using_keypad
```
work, or would the same issues arise? Also, I'm struggling to understand the last sentence on your response:
> But the semantics may be different, because `keypad` can be used in a non-blocking way.

I'd appreciate it if you could explain that to me.

**Comment by EGJ-Moorington** [comment]
Hello again! Just released [version 2.0.0](https://github.com/EGJ-Moorington/CircuitPython_Button_Handler/releases/tag/2.0.0), which uses `keypad` as the base of the library.

**Review by dhalbert — COMMENTED** [review]
Sorry I did not see this earlier. Libraries don't need to be reviewed before they're added to the bundle. I looked at the API briefly: the only thing I'd suggest is that instead of using strings to different button inputs, use some enum-like construct, like a set of integers, or maybe different objects. So for instance
```py
ButtonInput(ButtonInput.DOUBLE_PRESS, callback=double_press),
```
or maybe
```py
DoublePressInput(callback.double_press)
```

**Comment by EGJ-Moorington** [comment]
Thanks for the feedback! I added the changes in [version 3.0.0](https://github.com/EGJ-Moorington/CircuitPython_Button_Handler/releases/tag/3.0.0).

**Review by dhalbert — APPROVED** [review]
Thanks for this, and thanks for your patience during the review.

**Pull request merged**
