### PR TITLE
Add I2SInOut library

### PR DESCRIPTION
**Pull request by relic-se**
A general purpose driver for I2S devices. Allows read-only and bidirectional operation. Write-only operation is allowed as well, but not recommended in lieu of `audiobusio.I2SOut`. Requires CircuitPython 9.2.1.

_Because this library doesn't operate for a single device, it may be better placed within helpers. I'm also open to renaming this library in case it may create confusion with future additions to the CircuitPython core._

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I asked about the naming of this library during the weekly meeting today. The consensus was that it would be good to change the name slightly, but not necessarily due to possible conflict with a future core module. 

Can you rename the module to `pio_i2sinout` please? That way it will be apparent from the name that it's only supported on Raspberry Pi pico MCUs with PIO. This would follow essentially the same naming convention used by https://github.com/adafruit/Adafruit_CircuitPython_PIO_UART albeit with the "adafruit" pre-prended as well since it's an Adafruit library.

**Comment by FoamyGuy** [comment]
We also discussed helpers vs. drivers a bit, I think helpers is most appropriate for this library, though this one does sit sort of in the middle in that it's code that interfaces with hardware, but since it supports more than a single device helpers is more appropriate. PIO_UART was added under `helpers` in the adafruit bundle, so it'll be good to be consistent with that one.

**Comment by relic-se** [comment]
I love the suggestions, @FoamyGuy ! I'll make those adjustments soon to the library to get it more consistent with the practices of PIO_UART.

**Comment by relic-se** [comment]
@FoamyGuy Gotcha. I've got a new release published: https://github.com/relic-se/CircuitPython_PIO_I2S/releases/tag/1.1.0.

**Review by FoamyGuy — APPROVED** [review]
Thank you!

**Pull request merged**
