### PR TITLE
Fix Malformed URL To LTR559 Repo

### PR DESCRIPTION
**Pull request by sommersoft**
Found this while looking into https://github.com/adafruit/adabot/issues/181.

### CODE REVIEW

**Comment by ladyada** [comment]
thanx!

**Comment by sommersoft** [comment]
> Both _work_ as clone URLS with my version of git, but the new form is the one that github suggests when cloning via HTTP

The "malformation" was more about Adabot parsing the repo name from the `.gitmodules` entry, for the referenced issue. Git/GitHub will gladly re-direct with `.git`, `/`, and no ending in the URL. Apologies if use of "malformed" was the wrong term to use.

**Comment by jepler** [comment]
@Gadgetoid No action required on your part, but I wanted to call your attention to this.  It turns out submodule URLs need to be in a specific format when adding to the bundle.

**Comment by jepler** [comment]
@sommersoft Sorry, I didn't realize how pedantic what I was saying was.  I also didn't realize it actually fixed the problem.  Thanks!

**Comment by Gadgetoid** [comment]
Oooof - trust me to come bumbling in and break something! Achknowledged, thank you.

Is there any way to lint for this? It's the sort of thing I'm going to do so infrequently that I'll - if I'm being honest with myself - almost certainly make the same mistake again.

**Comment by sommersoft** [comment]
Just now seeing the replies.

> Sorry, I didn't realize how pedantic what I was saying was. I also didn't realize it actually fixed the problem. Thanks!

No worries, @jepler! As I said, my terminology/explanation could've been much better. 😄 

> Oooof - trust me to come bumbling in and break something! Achknowledged, thank you.
Is there any way to lint for this? It's the sort of thing I'm going to do so infrequently that I'll - if I'm being honest with myself - almost certainly make the same mistake again.

@Gadgetoid, breaking things is my whole approach. 😄 A linter/test could probably be worked up. Or, maybe Adabot could be more aware of different submodule URL formats, and handle all the ones that git/GitHub accept. The trailing `/` was the only issue, really.

**Pull request merged**
