### PR TITLE
Add VEML6070 UV Sensor library to bundle

### PR DESCRIPTION
**Pull request by sommersoft**
Added a VEML6070 UV sensor library.

[Adafruit VEML6070 UV Sensor Breakout](https://www.adafruit.com/products/2899) (Product ID: 2899)

### CODE REVIEW

**Comment by ladyada** [comment]
@sommersoft heya since this is an adafruit product and we were going to write a library, would you be cool with either transferring it to the adafruit acct (and being a collaborator) or having us fork it? that way we can help maintain :)

**Comment by sommersoft** [comment]
@ladyada I'm totally fine with either of those! Let me know what I need to do...

**Comment by ladyada** [comment]
hmm we'd rename it anyways so how about you try transferring it? we'll see if that works :D

**Comment by sommersoft** [comment]
Ok. I'm closing this PR so that it doesn't transfer with it. Also, I've removed my Travis & RTD. Coming to you shortly...

**Comment by ladyada** [comment]
yah - shoot - lets try that?

**Comment by sommersoft** [comment]
if that doesn't work, a fork or just grabbing the blob and starting a fresh repo seem to be the only options. like I said, I'm fine with any and all.

**Comment by ladyada** [comment]
the reason i cant fork is cause we'd rename it to match our style...
if you dont mind im going to just start it out and make you a contributor!

**Comment by sommersoft** [comment]
works for me!

**Comment by sommersoft** [comment]
and i'll delete my repo once yours is up.

**Comment by ladyada** [comment]
ok almost done, setting up travis, i just tweaked the name and cookiecutter (all our repos are named Adafruit_CircuitPython_XYZ to help corall them :)

**Comment by ladyada** [comment]
you can test out https://github.com/adafruit/Adafruit_CircuitPython_VEML6070 and then its moved!

**Comment by sommersoft** [comment]
"re-cookie". excellent commit -m! 😄 looks like it went well enough.

**Comment by ladyada** [comment]
lol i think its all good, i also tweaked example. i dont have the hardware with me so if you can try it out w/your breakout ill make a formal release!

**Comment by sommersoft** [comment]
can do.

**Comment by sommersoft** [comment]
works just the same. also, don't forget to update the README `Usage` code block before the release. I'd copy+paste from the example .py; I forgot to update the README after getting the example to pass Travis' superior standards.

**Comment by sommersoft** [comment]
And final note (putting it here for a matter of record): I only kept the BSD license based on your Arduino library that I used as the building block. Any additions I made can be considered under the MIT license.

**Comment by ladyada** [comment]
woops shoot did i mess something up with the license? which do you prefer? i dont care at all :)

**Comment by sommersoft** [comment]
you didn't mess anything up. GitHub default and the cookiecutter are set to MIT. the license statement at the beginning of the library has the BSD info... just need to change it, if you want. makes no difference to me either.

**Comment by ladyada** [comment]
fixed! we'll finish up travising, do a release and add to the main bundle. yayyy! please email pt@adafruit and for a gift :)

**Comment by tannewt** [comment]
FYI you can rename a repo after forking so that would have worked too.
Great work!

**Comment by ladyada** [comment]
really! i tried it once and couldnt but that was maybe a long time ago. oh well! next time :)

**Pull request closed without merging**
