### PR TITLE
Add CircuitPython_bteve as bteve

### PR DESCRIPTION
**Pull request by jamesbowman**
This adds the rest of the EVE support stack.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
I think the diff should also show the directory itself. Did you add it with `git submodule add`?

**Comment by tannewt** [comment]
I think you'll need to switch .gitmodules to https to fix the permission error and also tag a release in your repo (otherwise the auto-update code doesn't know what to do.)

**Comment by jamesbowman** [comment]
Oops, url fixed. And I tagged repo CircuitPython_bteve with 0.1.2

**Review by tannewt — APPROVED** [review]
Great! Thanks!

**Pull request merged**
