### PR TITLE
Add at42qt1070 driver library

### PR DESCRIPTION
**Pull request by skerr92**
Okay, this fixes the merge conflicts with .gitmodules and should be good to go.

Thanks!

### CODE REVIEW

**Comment by skerr92** [comment]
dang, it added .idea files. Will rm and add to gitignore

**Comment by ladyada** [comment]
hihi can you sync all the submodules? i dont think these other ones need to be updated, want to make sure they are not being regressed
https://github.com/adafruit/CircuitPython_Community_Bundle/pull/51/files

**Comment by skerr92** [comment]
```shell
(base) sethkerr@seths-MBP CircuitPython_Community_Bundle % git submodule sync
Synchronizing submodule url for 'libraries/drivers/adafruit_soundboard'
Synchronizing submodule url for 'libraries/drivers/at42qt107'
.
. (some information removed for brevity)
.
Synchronizing submodule url for 'libraries/helpers/parse'
Synchronizing submodule url for 'libraries/helpers/udecimal'
(base) sethkerr@seths-MBP CircuitPython_Community_Bundle % git add .
(base) sethkerr@seths-MBP CircuitPython_Community_Bundle % git commit -m "repushing after submodule sync"
On branch add_odt_at42qt1070
Your branch is up to date with 'origin/add_odt_at42qt1070'.

nothing to commit, working tree clean
(base) sethkerr@seths-MBP CircuitPython_Community_Bundle % ```

shows that things are up to date after syncing.

**Comment by tannewt** [comment]
You'll need to checkout the previous commits in the submodules that the PR shows you changed that are unrelated and then commit those versions.

**Comment by skerr92** [comment]
I'm gonna close this and then try one more time on a new branch :/

**Pull request closed without merging**
