### PR TITLE
TOML library

### PR DESCRIPTION
**Pull request by elpekenin**
As per title, library to read/dump data on TOML format. Is not fully compliant with the specification (doesn't aim for it anyway), but may come handy to work with data coming from the outside world or if a user wants something on `settings.toml` other than strings and integers

Let me know if i did something wrong (either on the PR itself or the repo's structure) and i will fix ASAP :)

### CODE REVIEW

**Comment by tannewt** [comment]
Looks like you need to make a release in your repo. That way it can find a tag for the commit.

**Comment by elpekenin** [comment]
> make a release 
I did (i believe): https://github.com/elpekenin/circuitpython_toml/releases/tag/0.1.3

**Review by tannewt — COMMENTED** [review]
That doesn't match the commit in this submodule (it is 5d6168 instead of ff1f4cd.)

**Comment by elpekenin** [comment]
Oops, thanks for the catch. Should i pull the tag or just the `main` branch?

**Comment by tannewt** [comment]
> Oops, thanks for the catch. Should i pull the tag or just the `main` branch?

The bundle uses the latest tag.

**Review by FoamyGuy — APPROVED** [review]
Thank you!

**Pull request merged**
