### PR TITLE
Add Arrow Line using vectorio

### PR DESCRIPTION
**Pull request by jposada202020**
PR to introduce new function helper to draw arrow using vectorio and bitmaptools.

Thanks

### CODE REVIEW

**Comment by kmatch98** [comment]
Wow, this is a great idea and looks really cool.  I've got a couple of suggestions depending upon what you're trying to achieve.

With the current version, you have two main steps
1. Line: "paint" the line into an existing bitmap
2. Arrow triangle: then create the `vectorio.Polygon` object
Having the two features with different behavior is a bit confusing to me.

If you want to "paint" lines into a bitmap (by paint I mean that you permanently change the bitmap by adding this line), then I think you should also "paint" in the triangle.

However, I think a better approach is to just create one `vectorio.Polygon` that draws both the line and the triangular arrow.  That way you can move this item independently of anything else on your screen.  To create this as a `vectorio.Polygon` you will need to calculate all seven points of this polygon, so it will require some geometry to figure it out.

I think it's a great idea, so it's cool that you are pursuing this.  I can imagine making Cartesian graphs with arrows on them!

**Comment by jposada202020** [comment]
@kmatch98 thanks, You are right, what a great idea, no excuses here, because I have not thought about that,. I had a lot of problems figuring out the geometry, calculations, so when developing I put the line and the the triangle in a different color to see what was going on. But in the calculations I have already all the points calculated in the code that are necessary to apply your wonderful idea.Thanks :).

**Comment by kmatch98** [comment]
I'm exactly the same way.  Whenever I try and do it all at once it usually takes longer (and is more frustrating) than breaking it into chunks and then pulling it all together.  Keep it up, I enjoy watching your progress and seeing what new tools you are building.

**Comment by jposada202020** [comment]
@kmatch98 
I did some test, in the pictures you could see the results using only Polygon and the original draw-line + Polygon
It is clear that it is necessary to ``trick`` vectorio.Polygon to draw a line, the problem arises in this small distances using discrete numbers. I think we will need and addition to vectorio that allows lines. or include a directional rectangle, at the moment. Other possibility is use Rotozoom,

## Original
image

## Modified
image

You could notice that the in the modified example the Triangle of the arrow are better drawn, this is because I used 5 points. First three points in the polygon, then go back to the top and then the base of the triangle. Discrete again making this weird :)

**Comment by kmatch98** [comment]
Yeah, it may be a rounding issue, I wonder if we can trick it somehow.  If you'd like I can look at your code and see if I can uncover any way to make it work.

**Comment by jposada202020** [comment]
@kmatch98 there you go it is the same function, i got ride of the documentations
```python
def line_arrow(grid, bitmap_s, x1, y1, x2, y2, arrow_length, palette, pal_index):

    # bitmaptools.draw_line(bitmap_s, x1, y1, x2, y2, pal_index)

    angle = math.atan2((y2 - y1), (x2 - x1))
    x0 = int(math.ceil(arrow_length * math.cos(angle)))
    y0 = int(math.ceil(arrow_length * math.sin(angle)))

    angle2 = math.pi / 2 - angle
    arrow_side_x = arrow_length // 2 * math.cos(angle2)
    arrow_side_y = arrow_length // 2 * math.sin(angle2)

    start_x = grid.x + x2
    start_y = grid.y + y2

    arrow_base_x = int(math.ceil(start_x - x0))
    arrow_base_y = int(math.ceil(start_y - y0))

    delta_right_x = int(math.ceil(arrow_base_x + 1))
    delta_right_y = int(math.ceil(arrow_base_y - 1))

    delta_left_x = int(math.ceil(arrow_base_x - 1))
    delta_left_y = int(math.ceil(arrow_base_y + 1))

    right_x = int(math.ceil(arrow_base_x + arrow_side_x))
    right_y = int(math.ceil(arrow_base_y - arrow_side_y))

    left_x = int(math.ceil(arrow_base_x - arrow_side_x))
    left_y = int(math.ceil(arrow_base_y + arrow_side_y))

    arrow_palette = displayio.Palette(2)
    arrow_palette.make_transparent(0)
    arrow_palette[1] = palette[pal_index]

    arrow = Polygon(
        points=[(start_x, start_y),
                (left_x, left_y),
                (right_x, right_y),
                (start_x, start_y),
                (arrow_base_x, arrow_base_y),
                (delta_right_x, delta_right_y),
                (grid.x + x1, grid.y + y1),
                (delta_left_x, delta_left_y),
                (arrow_base_x, arrow_base_y),

                ]
    )
    arrow_vector_shape = VectorShape(
        shape=arrow,
        pixel_shader=arrow_palette,
        x=0,
        y=0,
    )
    return arrow_vector_shape

```

**Comment by kmatch98** [comment]
Ok, here's a trial at a function that draws an angled rectange, and an example:

If you want to use this for your arrow, you will need to calculate the centerpoint of the arrow where the rectangle will touch it.  Or you can adapt this to make a 7-point polygon that draws the whole arrow as one polygon (maybe that would use less memory than two polygons), but either way will work.

I think the tricky part for me was figuring out to get the `xdiff` and `ydiff` values. I hope this will help.

```python
import math
from vectorio import Polygon

def AngledRectangle(x1, y1, x2, y2, stroke=1):
    if ((x2-x1) == 0):
        xdiff1 = round(stroke/2)
        xdiff2 = -round(stroke-xdiff1)
        ydiff1 = 0
        ydiff2 = 0

    elif ((y2-y1) == 0):
        xdiff1 = 0
        xdiff2 = 0
        ydiff1 = round(stroke/2)
        ydiff2 = -round(stroke-ydiff1)

    else:
        c=math.sqrt( (x2-x1)**2 + (y2-y1)**2)

        xdiff=stroke*(y2-y1)/c
        xdiff1=(round(xdiff/2))
        xdiff2=-round(xdiff-xdiff1)

        ydiff=stroke*(x2-x1)/c
        ydiff1=round(ydiff/2)
        ydiff2=-round(ydiff-ydiff1)
    #print("xdiff: {}, ydiff: {}".format(xdiff, ydiff))
    #print("xdiff1,2: {},{}, ydiff1,2: {},{}".format(xdiff1, xdiff2, ydiff1, ydiff2))

    polygon = Polygon(points=[(x1+xdiff1,y1+ydiff2), (x1+xdiff2, y1+ydiff1), (x2+xdiff2, y2+ydiff1), (x2+xdiff1, y2+ydiff2)])

    return polygon


import displayio
import board
import vectorio

display = board.DISPLAY

my_group = displayio.Group(max_size=3)

screen_palette = displayio.Palette(2)
screen_palette.make_transparent(0)
screen_palette[1] = 0x00AA00

line = AngledRectangle(40, 90, 40+20, 90-80, stroke=10)
line_shape = vectorio.VectorShape(shape=line, pixel_shader=screen_palette)
my_group.append(line_shape)

display.show(my_group)

while True:
    display.refresh()
    pass
```

**Comment by jposada202020** [comment]
@kmatch98 For sure I will check this out, it took you a couple of hours to figure this out, I took my three day to figure out the arrow, that is why you are the expert, I will take a look at that tomorrow night. Thanks kmtach :)

**Comment by kmatch98** [comment]
I’ve got a youngster high school geometry right now so I’ve been studying so I can keep up!

**Comment by jposada202020** [comment]
@kmatch98 Thanks, I did some tests, trying to  work with the 7 points polygon, not very satisfactory, I am guessing when it tries to draw inside the arrow it will dirt some pixels, so I took approach "aesthetics" and do two parts and packages in a group, Thank you for you contribution. Look how beautiful they are now
image

**Review by tannewt — CHANGES_REQUESTED** [review]
I think you need a release in your repo to make the CI pass here. (It checks for a release tag.)

**Comment by jposada202020** [comment]
@tannewt Thanks, I was not aware. I just did it. Thanks for the info

**Comment by jposada202020** [comment]
Replaced by PR #66

**Pull request closed without merging**
