### PR TITLE
WIP_add numpy-like interpolation

### PR DESCRIPTION
**Pull request by 95Fox**
This is to be a libarary .mpy for circuit python, circuit playground bluefruit boards.
It needs to use "bisect" in python to work correctly.
it interpolates between two numbers in a array and returns that value depending on the input value.
it is very similar to np.interp  in numpy.  and will be very useful for many applications that need to return a output value that is scaleed/mapped against a input value.  such as temperature gauges, pressure gauges, linear potentiometers etc...  any sensors with outputs

### CODE REVIEW

**Comment by tannewt** [comment]
@v923z Would it be possible to add this to `ulab`?

@95Fox `ulab` is a C module that would be faster than the mpy.

**Comment by v923z** [comment]
> @v923z Would it be possible to add this to `ulab`?
> 
> @95Fox `ulab` is a C module that would be faster than the mpy.

@tannewt Independent of this query, I started to work on porting `numpy`'s `interp` to `ulab`. I need a bit of time for optimising and cleaning it up, but I should be ready to release it early next week at the latest. I have created an issue, so that people can subscribe to it. https://github.com/v923z/micropython-ulab/issues/107

**Comment by 95Fox** [comment]
np.interp in numpy is even a better solution and works perfectly. its very easy to understand how to use it.  It would be greatly appreciated to add its functionality to a library

**Comment by 95Fox** [comment]
> 
> 
> @v923z Would it be possible to add this to `ulab`?
> 
> @95Fox `ulab` is a C module that would be faster than the mpy.

whichver you feel would be the best option, i am pretty new here, so i will follow your advise

**Comment by v923z** [comment]
> 
> I tired ulab, but it was not useable for a reason that i forget at the moment.

Well, this is not very specific;)

`ulab` is a software-only module, so if it failed for whatever reason, then it is most probably not `circuitpython`'s fault. Which means that you should raise the issue here: https://github.com/v923z/micropython-ulab/issues But `interp` is not yet implemented. As I said, I would need a couple of days to finish that.

**Comment by dhalbert** [comment]
I have been communicating with @95Fox about this on discord. If I remember right, it was just that `ulab` didn't have `interp` out of the box. I found another non-numpy implementation of linear interpolation, but it needed `bisect`.

**Comment by 95Fox** [comment]
Yes sorry.  To be more informative.  When imported  on the cpb board ulab did not have the bisect function.    Do you think you could notify me when the np.interp is ready.

**Comment by dhalbert** [comment]
@95Fox if you keep an eye on the ulab repo, you'll be able to track it. And if you open an issue there about adding interp, then it will be closed when it's added. That's the best way to get notified.

**Comment by tannewt** [comment]
@95Fox Are you ok if we close this? That way folks won't have two implementations to choose from.

**Comment by v923z** [comment]
> @95Fox if you keep an eye on the ulab repo, you'll be able to track it. And if you open an issue there about adding interp, then it will be closed when it's added. That's the best way to get notified.

The issue is already open, see above. 

@95Fox if you add a short comment there, you will be automatically notified, if anything changes.

**Comment by v923z** [comment]
> Yes sorry. To be more informative. When imported on the cpb board ulab did not have the bisect function. 

No one has asked for it, so I haven't implemented it yet.

**Comment by 95Fox** [comment]
> 
> 
> @95Fox Are you ok if we close this? That way folks won't have two implementations to choose from.

whatever is best for you guys.   initially i found np.interp to be perfect so as long as its functionality can be used soon...   is there any differences in "bisect" that it may be beneficial to have them both implemented?   maybe while its a hot topic it may be best to just do this one as well and get it done, in case someone decides to ask for it in a months time?  just thinking ahead

**Comment by v923z** [comment]
> whatever is best for you guys. initially i found np.interp to be perfect so as long as its functionality can be used soon... is there any differences in "bisect" that it may be beneficial to have them both implemented? 

I don't think so: `bisect` is a python library, and has nothing to do with `numpy`. I am not against adding math functions that do not conform to `numpy` (that is the `extras` sub-module for), but then those functions must be properly defined. 

In any case, if you want to open a discussion on that, I would really suggest that we continue on https://github.com/v923z/micropython-ulab.

**Comment by tannewt** [comment]
> > @95Fox Are you ok if we close this? That way folks won't have two implementations to choose from.
> 
> whatever is best for you guys. initially i found np.interp to be perfect so as long as its functionality can be used soon... is there any differences in "bisect" that it may be beneficial to have them both implemented? maybe while its a hot topic it may be best to just do this one as well and get it done, in case someone decides to ask for it in a months time? just thinking ahead

Cool! I'll close this because I think interp in ulab is a better option. We can do bisect separately as a python library or built in.

**Pull request closed without merging**
