### PR TITLE
Update PaletteSlice submodule definition

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
Change the folder name from camelcase to lowercase to make the library visible to `circup`.

### CODE REVIEW

**Review by tekktrik — APPROVED** [review]
Good catch!  I did some work to figure out if this will be automatically handled by `circup`, and it should as it just overwrites anything stored with a new copy of the entire bundle.  Anyone with a local version that they've acquired via `git clone` may need to remove the old folder if it's initialized, but that's totally fine.

**Comment by CedarGroveStudios** [comment]
Thanks for the review. I'm guessing that there will be very few local copies of the old folder, and given the specialized niche nature of the library, I suspect it won't be an issue. Also, I hadn't advertised its availability just yet (whew).

I'll test it and then close the related #127 where I asked Scott: "Would there ever be an instance where the submodule definition and path wouldn't be all lower-case? Should a check or correction be automated in the CI, perhaps?" What do you think about the viability of locking it down in the CI process?

**Comment by tekktrik** [comment]
Hmmm, that's a good question.  I typically Python libraries are lowercase, but it isn't necessarily enforced.  I would think it's worth doing in the cookiecutter but allowing someone to manually change it.  Is the error because the submodule name and actual `.py` folder aren't the same inclusive of case?

**Comment by CedarGroveStudios** [comment]
The change made it discoverable by circus. Back in business!

**Pull request merged**
