### PR TITLE
Add DFPlayer Pro DF1201S driver

### PR DESCRIPTION
**Pull request by aaronsilinskas**
This driver is for the DFPlayer Pro mini MP3 player with 128MB on-board storage. 

https://www.dfrobot.com/product-2232.html
https://wiki.dfrobot.com/DFPlayer_PRO_SKU_DFR0768

### CODE REVIEW

**Comment by aaronsilinskas** [comment]
Oh, should I only open a PR when I release 1.0.0?

**Comment by aaronsilinskas** [comment]
Will re-open after removing pre-release tag

**Comment by aaronsilinskas** [comment]
Apologies, I saw the issue. I didn't have a release for the latest `main` commit which is what the script wants.

**Review by tekktrik — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
