### PR TITLE
Add CedarGrove CircuitPython RangeSlicer helper class 

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
Add CedarGrove CircuitPython RangeSlicer helper class 

Range_Slicer is a general-purpose analog value converter that linearly scales the input then quantizes it into a collection of precise output slice values. The class detects input value changes and applies selectable hysteresis when slice edge thresholds are reached to eliminate dead-zone noise issues without filtering delays. Applications include converting rotary knob position to discrete ranges of MIDI values, analog signal noise processing, level detection, rotary switch emulation, and signal display.

For API and detailed functional description, see the original repo: https://github.com/CedarGroveStudios/Range_Slicer

### CODE REVIEW

**Review by tekktrik — CHANGES_REQUESTED** [review]
Looks like the CI wants a release, but otherwise looks good!

**Comment by Neradoc** [comment]
Thanks !
`circuitpython_community_library_list.md` is updated manually, please add the library to it, thanks.
https://github.com/adafruit/CircuitPython_Community_Bundle/blob/main/circuitpython_community_library_list.md

Oh and I note that your last two libraries were not added to the list either.

**Comment by tekktrik** [comment]
Whoops, that one's on me, I didn't realize the community bundle had it's own version of `drivers.rst`.  Sorry!

**Comment by Neradoc** [comment]
I believe that the issue is specifically that the PR targets a commit in the repo that is not a release itself (and happened before the releases).
> Submodule rangeslicer added at 82c301 

I think you want to run:
```sh
./update-submodules.sh
git add libraries/helpers/rangeslicer
git commit
git push
```

**Comment by CedarGroveStudios** [comment]
@Neradoc @tekktrik Thank you for the help! Let's hope it'll work this time around.

I still refer to Scott's `Creating and sharing a CircuitPython library` learning guide every time I submit something to the Community Bundle. The complicating factor is that I depend on GitHub desktop for managing my repos day-to-day which is especially useful for transparently handling auth tokens and passwords. GitCommandLineLand still feels like a text-based adventure game with magical incantations that I'm slowly learning to understand and remember.

**Review by Neradoc — APPROVED** [review]
Thanks, it's all good now 👍 
I thought the guide had been updated around the time a mention of the file was added to the readme here, I'll signal it.

**Comment by CedarGroveStudios** [comment]
> Looks like the CI wants a release, but otherwise looks good!

There was a release but an outstanding commit was holding up the works.

**Review by tekktrik — APPROVED** [review]
@Neradoc does the markdown file need to be updated then?  If not, it looks good to me!

**Pull request merged**
